### ISSUE TITLE
Version 1.1.3 - add function is broken

### ISSUE THREAD

**Issue by nchabra** [ipfs/node-ipfs-api#16]
The add method no longer works.
The simple test case is to run the 'add.js' example.
1.1.2 used to work

**Comment by jbenet** [comment]
Hm. We need tests on this stuff. @nchabra know why it broke? Happy to merge a pr and republish

cc @krl

**Comment by nchabra** [comment]
I'm working on writing tests and that's how I found it the problem.
Do you guys have favs for test frameworks?
Mocha/chai ok?

As for the problem, I could not see it easily, the last update had a shit load of cosmetic changes making the diff painful...

**Comment by jbenet** [comment]
No preferences on my end at this time. @travisperson @krl @STRML ?









—

**Comment by travisperson** [comment]
I would assume this has to do with `go-ipfs` and not this library.

**Comment by travisperson** [comment]
Appears to be an issue with a45397e5e26335c6008a8855208908f7aeb30359. Checking it out now, but I might be due to using single quotes in the http headers.

**Comment by whyrusleeping** [comment]
As for testing frameworks, i beleive @travisperson prefers mocha

**Comment by travisperson** [comment]
:+1:  yep!

**Comment by travisperson** [comment]
Pretty sure this is what's breaking it. Though even after fixing this I still can't get it to work.

```diff
+      if (typeof file === 'string') {
         // TODO: get actual content type
         mp.addPart({
           body: fs.createReadStream(file),
           headers: {
             'Content-Type': 'application/octet-stream',
-            'Content-Disposition': 'file; name="file"; filename="'+file+'"'
+            'Content-Disposition': 'file name=\'file\' filename=\'' + file + '\''
           }
-        });
+        })
 
-      } else if(Buffer.isBuffer(file)) {
+      } else if (Buffer.isBuffer(file)) {
         mp.addPart({
           body: file,
           headers: {
             'Content-Type': 'application/octet-stream',
-            'Content-Disposition': 'file; name="file"; filename=""'
+            'Content-Disposition': 'file name=\'file\' filename=\'\''
           }
-        });
+        })
       }
     }
```

**Comment by travisperson** [comment]
Alright fixed it. WIll be making a PR now.

**Comment by travisperson** [comment]
I also appear to have screwed up, and forgot to push back to master the last time I published, so some versioning is going to be a bit wacked.

@jbenet not sure how we should procced with this. On each PR that add additional functionallity I've been incrementing the minor version number, so on NPM we are `1.2.1`, as well as on github. It appears that pushing with the `--tags` flag only pushes tags.

**Comment by travisperson** [comment]
This is the fix; for reference. Once I get this version mix up fixed I'll proceed with the PR.

```diff
diff --git a/index.js b/index.js
index 4f950fe..3e1f8c7 100644
--- a/index.js
+++ b/index.js
@@ -29,9 +29,11 @@ module.exports = function (host, port) {
     var contentType = 'application/json'
     if (files) {
       var boundary = randomString()
-      contentType = 'multipart/form-data boundary=' + boundary
+      contentType = 'multipart/form-data; boundary=' + boundary
     }
 
+    console.log(contentType)
+
     if (typeof buffer === 'function') {
       cb = buffer
       buffer = false
@@ -117,7 +119,7 @@ module.exports = function (host, port) {
           body: fs.createReadStream(file),
           headers: {
             'Content-Type': 'application/octet-stream',
-            'Content-Disposition': 'file name=\'file\' filename=\'' + file + '\''
+            'Content-Disposition': 'file; name="file"; filename="' + file + '"'
           }
         })
 
@@ -126,7 +128,7 @@ module.exports = function (host, port) {
           body: file,
           headers: {
             'Content-Type': 'application/octet-stream',
-            'Content-Disposition': 'file name=\'file\' filename=\'\''
+            'Content-Disposition': 'file; name="file"; filename=""'
           }
         })
       }
```

**Comment by jbenet** [comment]
> On each PR that add additional functionallity I've been incrementing the minor version number

:+1: i should do this too

**Comment by krl** [comment]
Travis, good catch. i was being too reckless with search-replace.

Mocha can do e2e too?

**Comment by nchabra** [comment]
Mocha by itself is too simplistic for E2E, but used in conjunction with something else, the answer is yes.
I have used it with Protractor in angularjs testing and it worked nicely - but I'm no expert in this area

**Comment by travisperson** [comment]
I've been doing e2e with mocha and webdriver.io.

**Comment by nchabra** [comment]
Regarding tests, I had started writing a TypeScript declaration file .d.ts and tests in TS...
Now, I know TS is controversial, are you guys interested in seeing a PR with it? 
Or would you prefer keeping pure JS in which case I will just beautify the generated script once and take it from there.
Also, I added a little promisify function to work with Promises. Interested in that too?
If no no, then I'll adapt

**Comment by krl** [comment]
@nchabra feel free to make any pull requests you want, and we'll discuss in their respective threads!

Personally i'm open to looking at TS, even though i have not used it myself. Especially if you motivate why it fits in this case.

Thx!

**Comment by STRML** [comment]
AFAIK it doesn't play nice with React. But I would be very happy to be
proven wrong.

**Comment by nchabra** [comment]
I don't have anything really to defend TS in this case. There is no special fit to this project. Just a personal preference... There is quite a bit of extra-scaffolding to add, just to make my experiment easier. No point.
I'll continue my ipfs experiment with TS in my own fork for now.
Here is a gist with some ts2js generated tests in case you can salvage some stuff to get started.
https://gist.github.com/nchabra/840e37f1433d738a8851
Anyway, thanks for your time. This project is very exciting to me.

**Comment by jbenet** [comment]
In general, i like type safety. I've heard many good things about TypeScript. 

howver i think we should probably stay in pure js for small modules. it's the node way (tm).

then again, i don't really care, as long as _it just works_ for people, and nobody has to wrestle with it, im fine.

Also, that ts-generated js looks really good. it's better than much handwritten js :D

**Comment by travisperson** [comment]
I'm going to close this out as `1.1.4` fixes the issue.
