### ISSUE TITLE
Convert to use streams

### ISSUE THREAD

**Issue by travisperson** [ipfs/node-ipfs-api#21]
Currently everywhere in this module requires either a buffer or a file on disk to be used. I think we should switch to this take streams and allow the user to decide how to create that stream to pass in. This will greatly help with the `ipfs-blob-store` module, as well as allow this module to be more versatile.

Streams are easy to make from buffers and strings

```javascript
var stream = require('stream')
var buffer = new Buffer('foo')
var bufferStream = new stream.PassThrough()
bufferStream.end(buffer)
bufferStream.pipe(process.stdout)
```
*Source: http://stackoverflow.com/a/27964353/1489655*

Thoughts?

/cc @krl

**Comment by jbenet** [comment]
+1 to streams (streams2)

**Comment by krl** [comment]
Yes, this would be a clear improvement
