### ISSUE TITLE
Tests failing on CI

### ISSUE THREAD

**Issue by harlantwood** [ipfs/node-ipfs-api#24]
On [Circle CI](https://circleci.com/gh/ipfs/node-ipfs-api) the tests are failing to start up, in the before block:

```
npm test

> ipfs-api@1.1.8 test /home/ubuntu/node-ipfs-api
> mocha

pfs node api
    1) "before all" hook

  1) ipfs node api "before all" hook:
     Uncaught Error: spawn ENOENT
      at errnoException (child_process.js:1001:11)
      at Process.ChildProcess._handle.onexit (child_process.js:792:34)
```

Not sure why.  Googled some, but still not sure.  Anyone feeling more clueful on this?  @krl or @travisperson perhaps?

**Comment by harlantwood** [comment]
Tests work fine on my local machine.  I also opened up #23 to add Travis CI as well, so we can see if it's a Circle thing.

**Comment by jbenet** [comment]
one output bug:

```
pfs node api
```
(dont think this is related)

**Comment by jbenet** [comment]
failing to spawn a process-- wonder if they disallow it?

can always ask them

**Comment by harlantwood** [comment]
Hm, same error in Travis CI: https://travis-ci.org/ipfs/node-ipfs-api/jobs/65607666

Well, very similar at least:

```
  ipfs node api
  1) "before all" hook
  0 passing (21ms)
  1 failing
  1) ipfs node api "before all" hook:
     Uncaught Error: spawn ipfs ENOENT
      at exports._errnoException (util.js:746:11)
      at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
      at child_process.js:1144:20
```

**Comment by harlantwood** [comment]
I pinged both Circle and Travis to ask about this.

**Comment by harlantwood** [comment]
Circle said: 

> No, that should definitely be allowed. Not sure what is going on there; maybe try an ssh build to poke around at it?

Which I did, but no new info.  

One thought:  I am running on OSX, does anyone have a linux box handy where they can try running `npm test` on this repo?  Circle is on Ubuntu FWIW.

**Comment by jbenet** [comment]
i'd test it but clashes with nodes running. sadly all my linux boxes are running important things. maybe @travisperson or @krl can test?

**Comment by travisperson** [comment]
I develop on linux, it works for me.

**Comment by harlantwood** [comment]
This from Travis CI: 

> I don't think spawning is disallowed. What are the arguments passed to `child_process.spawn` in this case? The error message `ENOENT` seems to suggest it is looking for an executable that does not exist or is not accessible?

**Comment by travisperson** [comment]
Ah, ya. We are using an outdated version of the `ipfsd` package which doesn't use the shipped go-ipfs binary.

https://github.com/ipfs/node-ipfs-api/blob/master/package.json#L19

/cc @krl

**Comment by travisperson** [comment]
Looks like a version of ipfsd is released with the update so I made a PR.
