### ISSUE TITLE
Test config should use different ports

### ISSUE THREAD

**Issue by jbenet** [ipfs/node-ipfs-api#26]
would be nice if test config randomized ports or used different ports than default cause i cant run tests when my node is running

**Comment by travisperson** [comment]
I believe it does, have you ran into issues?

The testconfig.json file is not used right now, the tests start a disposable node which will pic a random port for the API to listen on.

**Comment by travisperson** [comment]
See: https://github.com/ipfs/node-ipfsd-ctl/blob/master/index.js#L189

I guess we need to also have it pick a different `swarm` port as well.

**Comment by krl** [comment]
@jbenet this should be fixed with #30, using tcp/0 for swarm as well
