### ISSUE TITLE
tests fail on master

### ISSUE THREAD

**Issue by NodeGuy** [ipfs/node-ipfs-api#32]
```shell
$ npm test

> ipfs-api@2.0.1 test /Users/david/Documents/Toptal/clients/Eris-Industries/node-ipfs-api
> mocha



  ipfs node api
    1) "before all" hook

  0 passing (4s)
  1 failing

  1) ipfs node api "before all" hook:
     Error: the object {
  "Code": 0
  "Message": "blockservice: key not found"
  "uncaught": true
} was thrown, throw an Error :)
  



npm ERR! Test failed.  See above for more details.
```

**Comment by jbenet** [comment]
@travisperson @krl thoughts?

**Comment by travisperson** [comment]
I'm not really sure. I can dig into it tonight though. @jbenet, @whyrusleeping can either of you comment on what might cause that error?

**Comment by jbenet** [comment]
it may be that the api is trying to get a key from the network, and the network is not connected.

**Comment by krl** [comment]
Hmm, i cannot reproduce this, running latest ipfs master, and latest node-ipfs-api.

@jbenet, @travisperson - could you reproduce?

**Comment by NodeGuy** [comment]
Since you couldn't reproduce it, I tried it again in a Docker container and it passed.  There must be something weird configured on my MacBook.  Sorry to bother you.
