### ISSUE TITLE
Compiling for the browser

### ISSUE THREAD

**Issue by jeffscottward** [ipfs/node-ipfs-api#37]
When compiling to a browser module, to then be imported to my app 
example... `import ipfsApi from 'ipfs-api/browser-ipfs';`
where I tuck the compiled `browser-ipfs` file inside the `node_modules/` folder and `import` aka `require`.

I get nothing. I log `ipfsApi` I get an empty object.

Can you provide a working example where its not just sitting as script tag in an html file, not sure if it works that way but thats what browserify suggest to do.

Would like to see it actually getting pulled into a proper ES6/Webpack/Gulp etc app that aims to spit out one JS file. Thats how modern development work for browsers these days.

Thanks!
Jeff

**Comment by jbenet** [comment]
@jeffscottward i think you just want:

```sh
npm install --save ipfs-api
```
then

```js
var ipfsApi = require('ipfs-api')
```

**Comment by jeffscottward** [comment]
No I do not.

When I do that it f course errors as it is looking for modules in the Node.js run time.
I get an error right away .

`Module not found: Error: Cannot resolve module 'fs'`
Which makes sense as `fs` is a native node module.  https://nodejs.org/api/fs.html#fs_file_system.

Where is your working example where you cited this error?
> If are using this module in a browser with something like browserify, then you will get an error saying that the origin is not allowed.

**Comment by jbenet** [comment]
Browserify or webpack should shim out the fs module just fine. We use browserify for the webui (https://github.com/ipfs/webui), which uses this module, and imports it as a usual node module. maybe take a look at that repo and its build pipeline? it used webpack until recently (we moved back to browserify).

**Comment by diasdavid** [comment]
I've added the need to execute the `brfs` transform on  on https://github.com/ipfs/node-ipfs-api/pull/38 , should solve the issue you described @jeffscottward

**Comment by diasdavid** [comment]
@jeffscottward try with the new version `2.1.0` - https://www.npmjs.com/package/ipfs-api

**Comment by diasdavid** [comment]
Other people have used it and seems to be working fine. @jeffscottward let me know if you still have problems using it on the browser and I'll reopen the issue.

**Comment by jeffscottward** [comment]
@diasdavid 

Ok thanks. Got side tracked.
Noticing though in Dev Tools console of Google Chrome

> The provided value 'ms-stream' is not a valid enum value of type XMLHttpRequestResponseType.
ipfsapi.min.js:3 
> The provided value 'moz-chunked-arraybuffer' is not a valid enum value of type XMLHttpRequestResponseType.

Can you remove this or account for them via browser feature sniffing?

**Comment by diasdavid** [comment]
@jeffscottward it's the first time I'm seeing that and I see it comes from browserify, not 100% sure why. Is this creating an error for you? Does your app break? Can you tell me more?

**Comment by jeffscottward** [comment]
It's just a warning. Doesn't break anything.
Idk what you mean specifically by "coming from browserify".
Browserify is injecting those warnings?

All I'm doing is  import ipfsApi from 'ipfs-api/ipfsapi.min.js';



On Fri, Aug 7, 2015 at 3:19 PM, David Dias <notifications@github.com> wrote:

> @jeffscottward <https://github.com/jeffscottward> it's the first time I'm
> seeing that and I see it comes from browserify, not 100% sure why. Is this
> creating an error for you? Does your app break? Can you tell me more?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipfs/node-ipfs-api/issues/37#issuecomment-128799440>.
>



-- 
*Thanks,*
*Jeff Ward*
*Front-end Developer*
*Tel: 516-551-8624*
*jsward.17@gmail.com <jsward.17@gmail.com>*
*@jeffscottward* <https://twitter.com/#!/jeffscottward>

**Comment by diasdavid** [comment]
Got it, we need to understand why browserify creates that log. `ms-stream` is a browserify dependency and when we generate the ipfsapi.min.js, we use browserify which adds that to the code

**Comment by jeffscottward** [comment]
Ok will google for a bit. I'm sure someone else has run into this.

**Comment by jeffscottward** [comment]
I don't believe browserify is "creating the log" per say. Chrome is flagging the code. Its coming from some required module that is outside the scope of node-ipfs-api source. Some where in one of these modules.

```
var fs = require('fs')
var path = require('path')
var http = require('http')
var qs = require('querystring')
var multiaddr = require('multiaddr')
var File = require('vinyl')
var MultipartDir = require('./multipartdir.js')
var stream = require('stream')
```

**Comment by jeffscottward** [comment]
Possibly related to this. Fetch API wasn't implemented yet and was a polyfill.
Thoughts?

http://stackoverflow.com/questions/15185499/webkit-equivalent-to-firefoxs-moz-chunked-arraybuffer-xhr-responsetype

**Comment by jeffscottward** [comment]
Progress on this?

**Comment by jbenet** [comment]
I think this is coming from browserify's patching. browserify modifies code to work on the browser. it's likely one of those modules?

**Comment by jeffscottward** [comment]
We ran into this again a year later. It is likely browserify. In Webpack we get native missing module errors which can be handled with
```
node: {
    console: 'empty',
    fs: 'empty',
    net: 'empty',
    tls: 'empty'
  }
```

===CLOSED===
