### ISSUE TITLE
please update README.md

### ISSUE THREAD

**Issue by acorbi** [ipfs/node-ipfs-api#46]
I am integrating node-ipfs-api with http://github.com/fedwiki/wiki-node and would be very thankful if the API documentation could be improved. Specifically, I would like to have the complete list of API methods with its docs and examples...

thanks!

**Comment by acorbi** [comment]
I see docs have been updated and extended a bit more. Keep on the good work!

**Comment by acorbi** [comment]
Thanks @RichardLitt for improving docs. I will then close this Issue and re-open (or open another one) in case I have the need for specific documentation.

**Comment by RichardLitt** [comment]
@acorbi No problem. I'm going to be continually reworking this, there is more to do here.
