### ISSUE TITLE
migrate to ipfs/ org and maintainer?

### ISSUE THREAD

**Issue by jbenet** [ipfs/node-ipfs-api#6]
Hey @mappum do you still want to maintain this? or hand it off to someone else?

Could we:
- [ ] migrate this repo to `ipfs` org?
- [x] add others (like @travisperson and @jbenet) as collabs in npm so we can publish?

thx

**Comment by mappum** [comment]
@jbenet I couldn't transfer ownership to ipfs, so I gave you collab access, LMK if that lets you transfer it.

I added you guys as owners of the NPM package.

**Comment by jbenet** [comment]
@mappum doesn't let me transfer-- what's the error you get?

(and thanks!)

**Comment by jbenet** [comment]
@mappum or could we go through me? send the repo to me and i'll push it to ipfs org? (no idea why it doesn't let you-- you're part of the org ...)

worst case we can fork it

**Comment by mappum** [comment]
@jbenet Cool, looks like I could transfer to you.

**Comment by jbenet** [comment]
@mappum :+1:

**Comment by jbenet** [comment]
(we can fork too-- your chocie)

**Comment by mappum** [comment]
Transferring is fine :+1:

**Comment by jbenet** [comment]
transformation complete

![](http://24.media.tumblr.com/tumblr_lzambxXknh1qczibyo1_500.gif)
