### ISSUE TITLE
Buffers are now implemented in pure JS

### ISSUE THREAD

**Issue by diasdavid** [ipfs/node-ipfs-api#60]
Node.js 4.1 came out and: 

> Buffers are now created in JavaScript, rather than C++. This increases the speed of buffer creation (Trevor Norris) #2866.
https://github.com/nodejs/node/blob/v4.1.0/CHANGELOG.md

This doesn't mean we will have the type Buffer as native in JS, but it does mean that the perf between browser and Node.js will be the same (or at least very close). 

Just wanted to make sure that one touches this module, knows it :) //cc @krl

**Comment by jbenet** [comment]
thanks for heads up @diasdavid
