### ISSUE TITLE
403 forbidden when post file from form

### ISSUE THREAD

**Issue by stadja** [ipfs/node-ipfs-api#61]
Hello to you all.
I am failry new with IPFS, and I am still strugling with things...

Right now, I am trying to make a very simple web service to post any file in ipfs.
Cool.

My apache configuration is the following:

- I have a domain: http://ipfs.stadja.net
- this domain is used to serve the html file post form AND the IPFS api.
- so in my domain I have a proxypass from / to my ipfs listening port
- and i have a /local alias to serve my form

my form is the following and is accessible at http://ipfs.stadja.net/local

	<form action="/api/v0/add" method="post" enctype="multipart/form-data">
	    Select image to upload:
	    <input type="file" name="fileToUpload" id="fileToUpload">
	    <input type="submit" value="Upload Image" name="submit">
	</form>

So when I submit my form, the response I have is:

    403 forbidden

Why ???????

My configuration works well,
http://ipfs.stadja.net/webui serves me the webui right... 
Any one have any idea ? :)

**Comment by jbenet** [comment]
Probably CORS. see  ipfs daemon --help



—

**Comment by stadja** [comment]
You, sir, ARE A FUNKY ROCKSTAR !!!

I am so happy right now :)

http://ipfs.stadja.net/local/

It Works.
So glad !

**Comment by whyrusleeping** [comment]
> FUNKY ROCKSTAR

![image](https://cloud.githubusercontent.com/assets/1243164/9954763/708c7d32-5da0-11e5-93c3-5a600b464649.png)

^ @jbenet right now

**Comment by jbenet** [comment]
finally catching up on something

![](http://www.scs.stanford.edu/~dm/enter.gif)

**Comment by mrcstvn** [comment]
Wondering if it makes sense to include the ipfs config commands that enable CORS headers in [/bin/container_daemon](https://github.com/ipfs/go-ipfs/blob/master/bin/container_daemon) so that when you initialize an IPFS node Docker container the webui can be accessed remotely without error.

**Comment by diasdavid** [comment]
@mrcstvn you can do that, through the cli and change the config (ipfs config --help) or even using the API: https://github.com/ipfs/js-ipfs-api/blob/master/tasks/daemons.js#L58 :)
