### ISSUE TITLE
ipfs.add(config.project, { recursive: true }, function (err, res) {}) is having a byzantine behaviour 

### ISSUE THREAD

**Issue by diasdavid** [ipfs/node-ipfs-api#70]
ipfs.add when in recursive mode fails, sometimes silently, sometimes with a EPIPE error

Example from ipsurge (which does `ipfs.add(config.project, { recursive: true }, function (err, res) {})` to the project folder

```
» ipsurge publish                                                                           
project: src/public
[ { Name: 'bootstrap-3.3.1/css/bootstrap-theme.css',
    Hash: 'QmYxvCd18WxWiKENoVaQWc28GWBZGa2fhTtFSRejhSwFj7' },
  { Name: 'bootstrap-3.3.1/css/bootstrap-theme.css.map',
    Hash: 'QmX6HipPP2vgx49MMkR6d5U3pocEZu6QJ3SpD72cWYaVbT' },
  { Name: 'bootstrap-3.3.1/css/bootstrap-theme.min.css',
    Hash: 'Qme5EFm8fgraoXKTUNDZZPJ6qdrjABxnyPQWUob5MsP1Gu' },
  { Name: 'bootstrap-3.3.1/css/bootstrap.css',
    Hash: 'QmVNfoG6KQ9bfkAi3Hj5vNGr6cB3NXHW3Vi9Wa4hVMCfgL' },
  { Name: 'bootstrap-3.3.1/css/bootstrap.css.map',
    Hash: 'QmRoVxqYhK8jgMedNwG8rCvvx6AbJzhBKx1tsRdv8ohV86' },
  { Name: 'bootstrap-3.3.1/css/bootstrap.min.css',
    Hash: 'QmfQorLd6NvVB53MKfSLGL2ZSgGZMWrF85qyWbB3vScvkX' },
  { Name: 'bootstrap-3.3.1/css',
    Hash: 'QmRFipREcWDPhSpxb5pEAbnxxRLcQgRoyxen5VWGyiZj4q' },
  { Name: 'bootstrap-3.3.1/fonts/glyphicons-halflings-regular.eot',
    Hash: 'Qmbn92gFfZ6Pte6NYgJisE4yBA7Km1zPbkW6xscpFBB9yX' },
  { Name: 'bootstrap-3.3.1/fonts/glyphicons-halflings-regular.svg',
    Hash: 'QmVYcwoiq3JeRHj38JhioijZju4ZJHHQZGbmpPykRtvD13' },
  { Name: 'bootstrap-3.3.1/fonts/glyphicons-halflings-regular.ttf',
    Hash: 'QmPrrwHNiSVDKn7xyLxkoeS9qQh3rkE96PfMGmTUTXQXx2' },
  { Name: 'bootstrap-3.3.1/fonts/glyphicons-halflings-regular.woff',
    Hash: 'Qmac6nKjPgEMDPg8MuEfgJskonyxLX5vR8phJ6cDqE9Zgc' },
  { Name: 'bootstrap-3.3.1/fonts',
    Hash: 'QmfYd1zuEoxjSK4FoH578vDQrfJ3zeM6EN52HWYP2EN7Ue' } ]
# note: there was more files to add, but it just exited
```

```
» ipsurge publish                                                                           
project: src/public
[ { Name: 'bootstrap-3.3.1/css/bootstrap-theme.css',
    Hash: 'QmYxvCd18WxWiKENoVaQWc28GWBZGa2fhTtFSRejhSwFj7' },
  { Name: 'bootstrap-3.3.1/css/bootstrap-theme.css.map',
    Hash: 'QmX6HipPP2vgx49MMkR6d5U3pocEZu6QJ3SpD72cWYaVbT' },
  { Name: 'bootstrap-3.3.1/css/bootstrap-theme.min.css',
    Hash: 'Qme5EFm8fgraoXKTUNDZZPJ6qdrjABxnyPQWUob5MsP1Gu' } ]
err { [Error: write EPIPE]
  code: 'EPIPE',
  errno: 'EPIPE',
  syscall: 'write',
  address: undefined }
```

Only works well with fewer files

**Comment by diasdavid** [comment]
@jbenet @mappum I've a memory of you fool proofing the vinyl-fs fixes by doing an add of the whole browserify folder during our stay in Berlin, but apparently it doesn't work anymore, any idea?

**Comment by diasdavid** [comment]
Added a failing test:

https://github.com/ipfs/node-ipfs-api/blob/issue70/test/test.js#L90-L101

Or if someone just wants to try it in normal non test script

```
var ipfsAPI = require('./src')('localhost', '5001')

var files = ['node_modules']

ipfsAPI.add(files, { recursive: true}, function (err, res) {
  if (err || !res) { 
    return console.error('err', err)
  }

  res.forEach(function (file) {
    console.log(file.Hash)
    console.log(file.Name)
  })
})
```

**Comment by diasdavid** [comment]
++ info 

tested with the older version of vinyl-fs-browser from Berlin, managed to actually ipfs add -r all the files, but not all the times. With version 0.1.0 of vinyl-fs-browser sometimes I get a `err { [Error: socket hang up] code: 'ECONNRESET' }`, wondering if this might actually be a problem from the go-ipfs side.

**Comment by diasdavid** [comment]
One more error that it randomly throws when running the test:

```
     Uncaught ENFILE: file table overflow, open '/Users/david/Documents/code/ipfs/node-ipfs-api/node_modules/browserify/node_modules/crypto-browserify/node_modules/public-encrypt/node_modules/parse-asn1/node_modules/browserify-aes/index.js'
  Error: ENFILE: file table overflow, open 'node_modules/browserify/node_modules/crypto-browserify/node_modules/public-encrypt/node_modules/parse-asn1/node_modules/browserify-aes/index.js'
      at Error (native)
```

Which kills the go-ipfs daemon, every remaining tests after that (if this error happens) throws:

```
Uncaught Error: connect ENFILE 127.0.0.1:52217 - Local (undefined:undefined)
```

**Comment by mappum** [comment]
I have been encountering this problem as well, but haven't been able to track it down. It's good to know that it only happens for recursive mode, I wasn't aware of that.

It seems that the problem goes away when using the api through a daemon spawned in `ipfsd-ctl`, it only happens for daemons spawned from an `ipfs daemon` command.

**Comment by diasdavid** [comment]
@mappum try to run the tests on [issue70 branch](https://github.com/ipfs/node-ipfs-api/tree/issue70), I see it failing, daemons spawned with ipfsd-ctl have the same issue

**Comment by diasdavid** [comment]
@mappum this seems to be a regression in go-ipfs itself, trying ipfs add -r with 0.3.8-dev gives me this result:

```
» ipfs add -r node_modules                                                                   
added QmXgrxnkEW56GyL62mj3zejqWV3zYXaaJPBTksXMQHePsa node_modules/brfs/LICENSE
added QmNanyfLgFdGfG4ca13rHXHBimPa8SCFMSC7KTAtF5yxu8 node_modules/brfs/bin/cmd.js
added QmZAAC51nCSAPoTrJtgj41vjgB5HXbsPjCMDfwW9GGFj5c node_modules/brfs/bin/usage.txt
added QmVETT9ogDEzFghCJtM5pATbDEJv2J6bwUA36xzfB97yaB node_modules/brfs/bin
added QmdDF5wsjSS1FDCBVZ47hLA69Gg37sgCyLekhXwZxEFt7R node_modules/brfs/example/async.js
added QmaKPhgS6UfmPiUVa3eaPJtkjoeZrcBAcn8XhEGgGD8ec4 node_modules/brfs/example/main.js
added QmbK4NYdVRH2JmzeuKqPxHhMTfPXV9tuxpprqFcKvfNoGX node_modules/brfs/example/robot.html
added Qmc8Hojw6pRrGyRey6ZQ2AqVQdPHLKVjknXAeFJkfbMn3W node_modules/brfs/example
added QmeqEczJbsNNWPKT72tLyBknEaTNxL2Jsf2vd9pFn4p2hC node_modules/brfs/index.js
6.92 KB / 81.06 MB [>-----------------------------------------------------------------------] 0.01 % 8m
» 
```

It simple exists at 0.01%

@whyrusleeping any ideas on what might have changed?

**Comment by mappum** [comment]
>this seems to be a regression in go-ipfs itself

Ah, that makes sense, my `ipfsd-ctl` must have been a working version of the daemon then.

**Comment by diasdavid** [comment]
@mappum what is the working version you have in ipfsd-ctl?

**Comment by mappum** [comment]
`ipfs version 0.3.7`

**Comment by diasdavid** [comment]
weird, the ipfsd-ctl that gets installed with node-ipfs-api comes with go-ipfs 0.3.7, and tests still fail:

```
» ./node_modules/ipfsd-ctl/node_modules/go-ipfs/bin/ipfs version                           
ipfs version 0.3.7
```

**Comment by diasdavid** [comment]
from @whyrusleeping 

> its an oldish issue
> its a result of us using too many file descriptors in our network stack

**Comment by whyrusleeping** [comment]
this issue has technically existed since the beginning of ipfs, but we havent noticed it until recently when our network started getting larger

**Comment by diasdavid** [comment]
Since `ipfsd-ctl` follows releases and not from master (thankfully!), this is not yet ready to be merged, nevertheless this shouldn't be as a problem as it was before, @whyrusleeping made it better

**Comment by diasdavid** [comment]
This is good now :) @whyrusleeping made go-ipfs better. Thanks Jeromy 🌟
